# NYC traffic accidents over a 4 year period 
## Filter and Subset

Download <a href="https://www.dropbox.com/s/585wrgl08djzlyt/accidents-nyc.csv?dl=0">this dataset</a> stored on dropbox.

In [2]:
## import necessary libraries
import pandas as pd

In [3]:
## read the dataset into notebook
traffic_acc = pd.read_csv("accidents-nyc.csv")

In [4]:
## see the overall info about this dataset
traffic_acc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282873 entries, 0 to 282872
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH DATE                     282873 non-null  object
 1   CRASH TIME                     282873 non-null  object
 2   BOROUGH                        282873 non-null  object
 3   NUMBER OF PERSONS INJURED      282873 non-null  int64
 4   NUMBER OF PERSONS KILLED       282873 non-null  int64
 5   NUMBER OF PEDESTRIANS INJURED  282873 non-null  int64
 6   NUMBER OF PEDESTRIANS KILLED   282873 non-null  int64
 7   NUMBER OF CYCLIST INJURED      282873 non-null  int64
 8   NUMBER OF CYCLIST KILLED       282873 non-null  int64
 9   NUMBER OF MOTORIST INJURED     282873 non-null  int64
 10  NUMBER OF MOTORIST KILLED      282873 non-null  int64
 11  CONTRIBUTING FACTOR VEHICLE 1  281489 non-null  object
 12  CONTRIBUTING FACTOR VEHICLE 2  224591 non-null  object
 13  COLLISION_ID                   282873 non-null  int64
 14  VEHICLE TYPE CODE 1            279986 non-null  object
 15  VEHICLE TYPE CODE 2            201168 non-null  object
dtypes: int64(9), object(7)
memory usage: 34.5+ MB

In [7]:
## create a series of crash dates.
traffic_acc["CRASH DATE"]

0         4/13/21
1         4/13/21
2         4/13/21
3         4/11/21
4         4/15/21
           ...
282868     1/1/19
282869     1/1/19
282870     1/1/19
282871     1/1/19
282872     1/1/19
Name: CRASH DATE, Length: 282873, dtype: object

In [5]:
## Which borough had the most crashes?
traffic_acc["BOROUGH"].value_counts()

BROOKLYN         95099
QUEENS           80085
BRONX            50123
MANHATTAN        48864
STATEN ISLAND     8702
Name: BOROUGH, dtype: int64

In [30]:
## which type of vehicle was primary vehicle involved in crashes?
## SHOW ONLY THE TOP 7

traffic_acc["VEHICLE TYPE CODE 1"].value_counts().head(7)

Sedan                                  129987
Station Wagon/Sport Utility Vehicle    102850
Taxi                                    10647
Pick-up Truck                            7183
Box Truck                                5504
Bus                                      4697
Bike                                     3177
Name: VEHICLE TYPE CODE 1, dtype: int64

In [31]:
## What were a FIVE unusual primary vehicles to get into a crash?
traffic_acc["VEHICLE TYPE CODE 1"].value_counts().tail(5)

SLINGSHOT     1
CHEVY EXPR    1
Go kart       1
FDNY Engin    1
MAC T         1
Name: VEHICLE TYPE CODE 1, dtype: int64

In [34]:
## create a subset of data for only Queens
## place it in a dataframe called df_q

df_q = traffic_acc[traffic_acc["BOROUGH"] == "QUEENS"]
df_q

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
2,4/13/21,17:30,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4408019,Sedan,Sedan
10,4/14/21,21:43,QUEENS,0,0,0,0,0,0,0,0,Turning Improperly,Unspecified,4407407,Station Wagon/Sport Utility Vehicle,NaN
17,4/15/21,14:30,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4407616,Sedan,Station Wagon/Sport Utility Vehicle
27,4/16/21,11:00,QUEENS,1,0,0,0,1,0,0,0,Turning Improperly,Unspecified,4407792,Station Wagon/Sport Utility Vehicle,Bike
28,4/16/21,17:00,QUEENS,5,0,0,0,0,0,5,0,Traffic Control Disregarded,Unspecified,4407853,Sedan,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282861,1/1/19,11:00,QUEENS,0,0,0,0,0,0,0,0,Unspecified,NaN,4065827,Sedan,NaN
282862,1/1/19,12:30,QUEENS,0,0,0,0,0,0,0,0,Unspecified,NaN,4062343,Sedan,NaN
282863,1/1/19,2:18,QUEENS,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4060413,Sedan,NaN
282864,1/1/19,13:00,QUEENS,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4060511,Sedan,Sedan
282866,1/1/19,10:23,QUEENS,1,0,0,0,0,0,1,0,Failure to Keep Right,Failure to Keep Right,4059208,Station Wagon/Sport Utility Vehicle,Sedan

In [35]:
## CHALLENGE (as in you have to google this)
## How many people were killed in Queens in accidents?
df_q["NUMBER OF PERSONS KILLED"].sum()

120

In [36]:
## Same
## how many cyclists were killed in Queens?
df_q["NUMBER OF CYCLIST KILLED"].sum()

8

In [38]:
## Filter and subset 
## create a dataset for Manhattan that involved taxi cabs as the primary vehicle cause

fil_borough = traffic_acc["BOROUGH"] == "MANHATTAN"
fil_car = traffic_acc ["VEHICLE TYPE CODE 1"] == "Taxi"
fil_car_two = traffic_acc ["VEHICLE TYPE CODE 2"] == "Taxi"

traffic_acc[fil_borough & fil_car & fil_car_two]

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
4718,7/18/21,4:11,MANHATTAN,3,0,0,0,0,0,3,0,Traffic Control Disregarded,Unspecified,4437909,Taxi,Taxi
5561,5/4/21,17:55,MANHATTAN,2,0,0,0,0,0,2,0,Following Too Closely,Unspecified,4415728,Taxi,Taxi
5985,5/14/21,20:20,MANHATTAN,1,0,0,0,0,0,1,0,Passing or Lane Usage Improper,Driver Inattention/Distraction,4416587,Taxi,Taxi
7665,5/20/21,21:40,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4419674,Taxi,Taxi
9826,5/31/21,9:36,MANHATTAN,1,0,0,0,0,0,1,0,Driver Inattention/Distraction,Unspecified,4422842,Taxi,Taxi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281498,1/4/19,14:20,MANHATTAN,0,0,0,0,0,0,0,0,Passing or Lane Usage Improper,Passing or Lane Usage Improper,4062097,Taxi,Taxi
281643,1/5/19,19:00,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4062106,Taxi,Taxi
281838,1/3/19,15:10,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unsafe Lane Changing,4061526,Taxi,Taxi
281997,1/5/19,21:37,MANHATTAN,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,4062424,Taxi,Taxi
282453,1/5/19,22:00,MANHATTAN,3,0,0,0,0,0,3,0,Traffic Control Disregarded,Unspecified,4062852,Taxi,Taxi

In [40]:
## What were the top 5 causes of accidents across all the boroughs?
## by primary vehicle cause


traffic_acc["CONTRIBUTING FACTOR VEHICLE 1"].value_counts().head(5)

Unspecified                       78494
Driver Inattention/Distraction    70615
Failure to Yield Right-of-Way     20691
Following Too Closely             14407
Backing Unsafely                  13348
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [41]:
## What were the top 5 causes of accidents across all the boroughs?
## by secondary vehicle cause

traffic_acc["CONTRIBUTING FACTOR VEHICLE 2"].value_counts().head(5)

Unspecified                       190456
Driver Inattention/Distraction     14186
Other Vehicular                     3529
Failure to Yield Right-of-Way       2233
Passing or Lane Usage Improper      2171
Name: CONTRIBUTING FACTOR VEHICLE 2, dtype: int64

In [42]:
## What were the 5 RAREST causes for primary vehicles causing the accident

traffic_acc["CONTRIBUTING FACTOR VEHICLE 1"].value_counts().tail(5)

Shoulders Defective/Improper    13
Texting                          8
Cell Phone (hands-free)          8
Windshield Inadequate            3
Listening/Using Headphones       2
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [55]:
## list ALL the causes as unique values (in other words, create a list of the causes)
## WHAT ARE SOME UNUSUAL REASONS FOR ACCIDENTS?
traffic_acc["CONTRIBUTING FACTOR VEHICLE 1"]

0                            Unspecified
1                  Following Too Closely
2         Driver Inattention/Distraction
3                    Passing Too Closely
4                            Unspecified
                       ...
282868    Driver Inattention/Distraction
282869                  Steering Failure
282870                       Unspecified
282871               Passing Too Closely
282872    Driver Inattention/Distraction
Name: CONTRIBUTING FACTOR VEHICLE 1, Length: 282873, dtype: object